### ISSUE TITLE
大佬 能开发那个说话人日志的功能吗？

### ISSUE THREAD

**Issue by zuowanbushiwo** [lovemefan/paraformer-python#2]
你好
      这个说话人日志的功有计划吗？

**Comment by lovemefan** [comment]
你好，有这个打算，但是目前我个人时间不太充足，进度缓慢。当然也欢迎贡献代码。如果着急使用的话，官方已经提供了相关代码[Paraformer分角色语音识别-中文-通用
](https://modelscope.cn/models/damo/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn/summary)。

目前我的这个项目有说话人识别功能，返回说话人id，[代码在这](https://github.com/lovemefan/paraformer-python/blob/main/paraformer/runtime/python/model/sv/campplus.py)。是将vad片段送入说话人识别模型，效果不理想。

希望以上对你有帮助

**Comment by lovemefan** [comment]
> 你好 感谢回复，现在用的pyannote 的 speaker Diarization 效果感觉不太好，这个会比pyannote 准确吗？开发这个功能感觉对我很困难，把握不住。

我没有用过pyannote，没有比较过两者.但是我找到查找pyannote时，在[paper with code](https://paperswithcode.com/paper/speaker-embedding-aware-neural-diarization-a)发现有更新的工作  , 模型是SOND， 对应[魔搭社区](https://www.modelscope.cn/models/damo/speech_diarization_sond-zh-cn-alimeeting-16k-n16k4-pytorch/summary), 对应[代码](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/models/e2e_diar_sond.py) 。在alimeeting数据集上效果更好。

**Comment by lovemefan** [comment]
> https://www.modelscope.cn/models/damo/speech_diarization_sond-zh-cn-alimeeting-16k-n16k4-pytorch/summary 这个模型是也是做说话人日志的吗？

是的， 阿里的开源工作一部分在[3D-Speaker](https://github.com/alibaba-damo-academy/3D-Speaker/tree/3dspeaker/egs/3dspeaker/speaker-diarization)，一部分在Funasr的[SOND](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/models/e2e_diar_sond.py)， [eend_ola](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/models/e2e_diar_eend_ola.py)中

**Comment by lovemefan** [comment]
> [eend_ola](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/models/e2e_diar_eend_ola.py) 是什么？检查语音重叠部分的吗？这个有预训练模型吗？ 谢谢！

这个工作我也不太熟，我稍微看了下，是能够适应多说话人重叠的情况。另外在[魔搭](https://www.modelscope.cn/models/damo/speech_diarization_eend-ola-en-us-callhome-8k/summary)上有,所有的说话人日志分类都在[这里]((https://www.modelscope.cn/models?page=1&tasks=speaker-diarization&type=audio))

**Comment by lovemefan** [comment]
> 还有你上面提到的这个 [Paraformer分角色语音识别-中文-通用 ](https://modelscope.cn/models/damo/speech_paraformer-large-vad-punc-spk_asr_nat-zh-cn/summary) 也有speaker Diarization功能，虽然不是这个模型主要的功能，如果ASR的结果有时间戳，应该也是可以做 speaker Diarization，不知道对不对？ 而且看介绍和上面的 [3D-Speaker](https://github.com/alibaba-damo-academy/3D-Speaker/tree/3dspeaker/egs/3dspeaker/speaker-diarization)，[SOND](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/models/e2e_diar_sond.py)， [eend_ola](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/models/e2e_diar_eend_ola.py) 好像都不一样，这个是不是在更大的数据(60000小时)上训练的，而且和ASR联合训练的，有没可能效果更好？当然需要更多计算资源。

1. paraformer分角色语音识别是级联多个模块的系统。
2. ASR有没有时间戳我觉得和说话人日志没有太大关系。就算根据时间戳来切分句子也有可能包含多个说话人的，举个例子，两人对话的场景，如果两个人对话切换的时间较短时，仅靠vad是区分不出来的。
3. 经验上来说，数据越大效果是越好的。对于推理来说，计算资源主要取决于模型参数量大小，和用的多少数据训练的无关。我使用过ERes2Net-Large，相比于cam++效果要好，但是参数量大约10倍。

希望以上能帮助你

**Comment by lovemefan** [comment]
> 非常感谢你的耐心回答，祝您心想事成，工作科研顺利

不客气😊，欢迎交流。补充一点之前没看清楚。上面提到的6w小时数据是asr的。不是联合训练的哈，是分开训练的。
