### ISSUE TITLE
内存泄漏严重

### ISSUE THREAD

**Issue by James-jordan-coder** [lovemefan/paraformer-python#3]
大佬，长时间运行程序后，运行内存持续增长还不释放，内存泄漏严重。

**Comment by lovemefan** [comment]
> 大佬，长时间运行程序后，运行内存持续增长还不释放，内存泄漏严重。

你好👋，争取周末修复

**Comment by James-jordan-coder** [comment]
1、采集麦克风发数据，试过几个小时
2、读取文件，随机的读取过几个文件（几分钟的，几十分钟的都有）
单个客户端会出现。
试过多个客户端，时间长点就会发现内存不停的上涨。
2种情况结束后内存好像也没有释放。

**Comment by lovemefan** [comment]
![newplot](https://github.com/lovemefan/paraformer-python/assets/22907863/5889dd3d-9dce-4538-8cf4-5676025cd6a7)

如上图，存在内存未释放现象

<img width="1485" alt="image" src="https://github.com/lovemefan/paraformer-python/assets/22907863/be824701-5efa-4db0-9f01-2b12871aa947">
目前已找到未释放内存的代码，待修复

**Comment by lovemefan** [comment]
经bug 修复后，测试30分钟音频，重复10次内存测试，内存变化如下图所示
![WX20240215-104239@2x](https://github.com/lovemefan/paraformer-python/assets/22907863/2000a45a-7c63-468f-b992-fc0c85e81fc9)

**Comment by lovemefan** [comment]
内存泄漏bug已修复，因为个人时间原因拖更至今，感谢提出宝贵的意见。
