### ISSUE TITLE
关于model_quant_1.onnx量化细节

### ISSUE THREAD

**Issue by liziru** [lovemefan/paraformer-python#4]
你好大佬，感谢你的工作！如标题，我想请教一下，带quant标识的模型应该做了量化了吧，是int8量化吗，还是int4量化？ @lovemefan

**Comment by lovemefan** [comment]
你好，模型是使用funasr官方仓库代码导出的部分int8量化版本， 具体细节在[此处](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/utils/export_utils.py#L53-L68),  文档在[这](https://github.com/alibaba-damo-academy/FunASR/blob/main/docs/tutorial/README.md#export-onnx)

**Comment by leospark** [comment]
> 你好，模型是使用funasr官方仓库代码导出的部分int8量化版本， 具体细节在[此处](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/utils/export_utils.py#L53-L68), 文档在[这](https://github.com/alibaba-damo-academy/FunASR/blob/main/docs/tutorial/README.md#export-onnx)

好的，感谢！

**Comment by lovemefan** [comment]
> > 你好，模型是使用funasr官方仓库代码导出的部分int8量化版本， 具体细节在[此处](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/utils/export_utils.py#L53-L68), 文档在[这](https://github.com/alibaba-damo-academy/FunASR/blob/main/docs/tutorial/README.md#export-onnx)
> 
> 好的，感谢！

不客气😊
